#!/bin/bash
set -xeuo pipefail
cd "`dirname "$0"`/.."

ASSETS_PATH="/c/Program Files (x86)/Grinding Gear Games/Path of Exile"
# ls "$ASSETS_PATH"
pypoe_exporter config set ggpk_path "$ASSETS_PATH"

mkdir -p build
pypoe_exporter dat json build/poe.json
