#!/bin/bash
# set -x
set -euo pipefail
cd "`dirname "$0"`/.."
mkdir -p dist/dat

ASSETS_EXE_PATH="./assets/exe/depot"
[ ! -f ./third-party/strings/strings.exe ] && unzip third-party/Strings.zip -d third-party/strings
./third-party/strings/strings.exe -accepteula 2>/dev/null || true
POE_VERSION="`./third-party/strings/strings.exe "$ASSETS_EXE_PATH/PathOfExileSteam.exe" | grep release/tags/ | sed -e "s_release/tags/__"`"
if [ -z $POE_VERSION ]; then
  echo "Failed to find poe version"
  exit 1
fi
echo "${POE_VERSION}" | tee dist/version.txt
echo "{\"version\":\"${POE_VERSION}\"}" > dist/version.json

# ASSETS_PATH="/c/Program Files (x86)/Grinding Gear Games/Path of Exile"
ASSETS_PATH="./assets/content/depot"
pypoe_exporter config set ggpk_path "$ASSETS_PATH"

# Build a list of dat files
cp patch/index_dat.py third-party/PyPoE/PyPoE/index_dat.py
python third-party/PyPoE/PyPoE/index_dat.py > dist/index_dat.json
rm -f third-party/PyPoE/PyPoE/index_dat.py

# Apply a PyPoE patch that skips files with errors. Too underdeveloped for a
# PyPoE pull request - it'd need a cli flag, at least - so I'll maintain a patch
# file for now.
git apply third-party/PyPoE.patch
# pypoe_exporter dat json dist/all.json >dist/all-out.txt 2>dist/all-err.txt
pypoe_exporter dat json dist/all.json
git checkout third-party/PyPoE

# Split all.json into a file per dat file
node scripts/dist.js
