#!/bin/bash
set -xeuo pipefail
cd "`dirname "$0"`/.."

pip install -r third-party/steampull/requirements-win.txt
(cd third-party/PyPoE && pip install -e .[cli-full])
# github-pages publishes our whole site (because it's easy), but whines about .exe files
cp -p third-party/ooz.exe_ ./ooz.exe
