name: assets-export
on:
  schedule:
    - cron: "5 1 * * *"
  workflow_dispatch:

jobs:
  # windows must run this, not ubuntu, as pypoe/our datamine export depends on packages/datamine/ooz.exe
  fetch:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: |
          echo "::add-mask::${{ secrets.STEAMPULL_USER }}"
          echo "::add-mask::${{ secrets.STEAMPULL_PASSWD }}"
          echo "::add-mask::${{ secrets.STEAMPULL_SECRET }}"
      - uses: actions/checkout@v2
      # https://github.com/marketplace/actions/setup-python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install --frozen-lockfile

      # fetch poe content, if it's changed
      - env:
          STEAMPULL_USER: ${{ secrets.STEAMPULL_USER }}
          STEAMPULL_PASSWD: ${{ secrets.STEAMPULL_PASSWD }}
          STEAMPULL_SECRET: ${{ secrets.STEAMPULL_SECRET }}
        run: yarn fetch:auth
      - run: yarn fetch
      - run: |
          echo 'STEAM_DEPOT_INFO_DIFF<<__EOF__' >> $GITHUB_ENV
          (diff assets/content/info-old.txt assets/content/info.txt || true) >> $GITHUB_ENV
          echo '__EOF__' >> $GITHUB_ENV
          cat $GITHUB_ENV
      - run: echo "POE_VERSION=`cat dist/version.txt`" >> $GITHUB_ENV

      # extract json from poe content, if it's changed
      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        run: yarn dist

      # https://peterevans.dev/posts/github-actions-how-to-create-pull-requests-automatically/
      - if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
        name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: workflows-assets-export
          commit-message: '[assets-export] Path of Exile patch ${{ env.POE_VERSION }}'
          title: '[assets-export] Path of Exile patch ${{ env.POE_VERSION }}'
          body: >
            Looks like Path of Exile was patched recently! I've updated pypoe-json for you. New version: ${{ env.POE_VERSION }}.

            This PR was auto-generated by the [assets-export robot](https://github.com/erosson/pypoe-json/actions?query=workflow%3Aassets-export).
          labels: automated pr
