# Notify our dependents when pypoe-json changes, so they can rebuild immediately.
# Feel free to send a PR adding your repo to the list: notify-on-change-repos.txt
name: notify-on-change
on:
  push:
    branches: [master]
    paths:
      - "dist/**"
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      # https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#create-a-repository-dispatch-event
      - run: |
          for $REPO in `cat .github/workflows/notify-on-change-repos.txt`; do
            echo $REPO
            curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/$REPO/dispatches \
              -d '{"event_type":"pypoe-json_build"}'
          done
